
services:
  frontend:
    build:
      context: ./client
    container_name: frontend
    command: sh -c "npm run build && cp -r dist/* /app-dist && chmod -R 755 /app-dist"
    volumes:
      - frontend_build:/app-dist
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./server
    container_name: backend
    restart:  unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mern-recipes
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - my_network

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

volumes:
  mongo_data:
  frontend_build:

networks:
  my_network:
    driver: bridge