
services:
  frontend:
    build:
      context: ./client
    container_name: frontend
    restart:  unless-stopped
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./server
    container_name: backend
    restart:  unless-stopped
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mern-recipes
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - my_network

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my_network

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./client/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network:
    driver: bridge